spring:
  zipkin:
    base-url: http://localhost:8763
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:33060/scloud_demo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
